FROM node:16-alpine

# Create a working directory
WORKDIR '/app' 

# Copy package.json to the working directory
COPY package.json .

# Install dependencies
RUN npm install

# Copy the rest of the files to the working directory
COPY . .

# Start the app
CMD ["npm", "run", "start"]




